Spike/collective lift and shift updates
epimorphics/ppd-explorer pull request #188
Opened 2023-01-24 14:58 UTC by jonrandahl

2023-03-13 13:52 UTC, bogdanadrianmarc approved these changes
Looks good 👍

2023-03-13 15:12 UTC, der approved these changes
Looks fine, just one comment in line.

2023-03-13 15:12 UTC, der commented on Dockerfile
> +COPY .bundle/config /root/.bundle/config
What's the reason for dropping the previous `set --local without 'development test'`?  Just going by the name, with no knowledge of bundle config, sounds like you would want those omitted.

2023-03-13 15:33 UTC, jonrandahl commented on Dockerfile
> +COPY .bundle/config /root/.bundle/config
Thanks @der I'm actually investigating that at the moment as I noted massive differences with the dockerfiles in all the LR Apps...

2023-03-21 13:03 UTC, jonrandahl commented on Dockerfile
> +COPY .bundle/config /root/.bundle/config
> passing the --without flag to `bundle-install` prevents Bundler from installing certain groups specified in the `Gemfile`. Bundler persists this value  in  app/.bundle/config  so that calls to Bundler.setup do not try to find gems from the  Gemfile that you didn't install.  Additionally, subsequent calls to bundle install remember this setting and skip those groups. [^1]

So in this case it prevents the development and test grouped gems from installing unnecessarily. 

[^1]: https://manpages.ubuntu.com/manpages/bionic/man1/bundle-config.1.html

2023-03-21 17:41 UTC, andrew-pickin-epi requested changes

2023-03-21 17:41 UTC, andrew-pickin-epi commented on Makefile
> +TAG?=$(shell printf '%s_%s_%08d' ${VERSION} ${COMMIT} ${GITHUB_RUN_NUMBER})
Has it been confirmed that changing the Tag format doesn't break deployment?

2023-03-21 17:41 UTC, andrew-pickin-epi commented on README.md
> +| `APPLICATION_ROOT`         | The path from the server root to the application                     | `/app/ppd`                 |
NO. This shouldn't be an environment variable unless the image has no knowledge of the path from build time. I VERY much suspect this is not the case.

What does "Typical Value" mean?

2023-03-21 17:41 UTC, andrew-pickin-epi commented on entrypoint.sh
> +export RAILS_RELATIVE_URL_ROOT=${APPLICATION_ROOT:-'/app/ppd'}
No. Don't use environment variables.

2023-03-21 17:41 UTC, andrew-pickin-epi commented on entrypoint.sh
> +echo "{\"ts\": $(date -u +%FT%T.%3NZ), \"level\": \"INFO\", \"message\": \"Starting ${PUBLIC_NAME} application with RAILS_ENV=\"${RAILS_ENV}\", \"RAILS_RELATIVE_URL_ROOT\"=\"${RAILS_RELATIVE_URL_ROOT
No. Don't use environment variables.

2023-03-21 19:05 UTC, der approved these changes
Looks fine to me apart from not understanding the point of `SCRIPT_NAME`.

Don't understand @andrew-pickin-epi 's concern about use of environment variable to set `RAILS_RELATIVE_URL_ROOT` but once that's resolved to mutual satisfaction I don't think I need to re-review so approving now.

2023-03-21 19:05 UTC, der commented on entrypoint.sh
>  export SCRIPT_NAME=${RAILS_RELATIVE_URL_ROOT}
Is this needed? I thought we only used `RAILS_RELATIVE_URL_ROOT`

2023-05-15 15:47 UTC, andrew-pickin-epi requested changes
I suspect there a broken merge going on here. 
The `Makefile` is certainly in error.

2023-05-15 15:47 UTC, andrew-pickin-epi commented on CHANGELOG.md
> +  also includes adjustments to not double render the error response.
APPLICATION_ROOT has been dropped.

2023-05-15 15:47 UTC, andrew-pickin-epi commented on README.md
> +| `APPLICATION_ROOT`         | The path from the server root to the application                     | `/app/ppd`                 |
APPLICATION_ROOT has been dropped.

2023-05-15 15:47 UTC, andrew-pickin-epi commented on Makefile
> +TAG?=$(shell printf '%s_%s_%08d' ${VERSION} ${COMMIT} ${GITHUB_RUN_NUMBER})
This still using the  wrong path for the bundle conf.
Broken merge?

2023-05-22 16:28 UTC, andrew-pickin-epi approved these changes

2023-05-23 08:11 UTC, merged